import { questions } from './data/questions.js';
import { levels } from './data/levels.js';
import { isAllowedWorkspaceEmail, maskEmail } from './lib/domain.js';
import { fieldCounts, isPassing, nextCertificateNumber, normalizeUsername, remainingAttempts, sanitizeForClient, saveSound, saveTheme, selectQuestions, tokyoDateKey, type Theme } from './lib/rules.js';
let view='home', theme=(localStorage.getItem('theme') as Theme)||'light', sound=localStorage.getItem('sound')==='on', reduced=false, passed=false, cert='';
let audioContext: AudioContext | undefined;
const user={email:'demo@wasegaku.ac.jp',name:'クエスト参加者',role:'生徒',school:'わせがく高等学校'}; const answers:Record<string,number>={}; const selected=selectQuestions(questions,new Set(['l1-q01','l1-q07']),()=>0.42); const clientQuestions=selected.map(sanitizeForClient);
async function beep(score:number){ if(!sound) return; audioContext ??= new AudioContext(); const ctx=audioContext; if(ctx.state==='suspended') await ctx.resume(); const osc=ctx.createOscillator(); const gain=ctx.createGain(); osc.frequency.value=score>=10?880:score>=8?740:score>=5?520:score>=2?360:260; gain.gain.setValueAtTime(0.0001,ctx.currentTime); gain.gain.exponentialRampToValueAtTime(.12,ctx.currentTime+.02); gain.gain.exponentialRampToValueAtTime(0.0001,ctx.currentTime+.28); osc.connect(gain); gain.connect(ctx.destination); osc.start(); osc.stop(ctx.currentTime+.3); }
function total(){return Object.values(answers).reduce((a,b)=>a+b,0)} function h(s:string){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}
function fieldSummary(){ const counts=fieldCounts(selected); return `ICT関連 ${counts.ict}問 / AI関連 ${counts.ai}問 / ICT・AI総合 ${counts.integrated}問`; }
function fieldLabel(field:'ict'|'ai'|'integrated'){ return field==='ict'?'ICT関連':field==='ai'?'AI関連':'ICT・AI総合'; }
function fieldAdvice(field:'ict'|'ai'|'integrated'){ return field==='ict'?'パスワード、個人情報、著作権、情報の信頼性を、学校生活の場面に置き換えて確認しましょう。':field==='ai'?'AIの出力をそのまま信じず、根拠確認、個人情報を入力しない判断、バイアスへの注意を意識しましょう。':'「情報が足りない時は確認する」「同意や条件を確かめる」など、ICTとAIを組み合わせた判断を練習しましょう。'; }
function resultAdvice(){ const scores={ict:0,ai:0,integrated:0}; const counts=fieldCounts(selected); selected.forEach(q=>{scores[q.field]+=answers[q.id]??0}); const fields=(Object.keys(scores) as Array<'ict'|'ai'|'integrated'>); const rate=(field:'ict'|'ai'|'integrated')=>counts[field]===0?0:scores[field]/(counts[field]*10); const best=fields.reduce((a,b)=>rate(a)>=rate(b)?a:b); const weak=fields.reduce((a,b)=>rate(a)<=rate(b)?a:b); const score=total(); const summary=isPassing(score)?'合格ラインを超えています。基本的な知識に加えて、状況に応じて確認・相談する判断ができています。':score>=70?'合格まであと一歩です。知識は身についてきていますが、判断が分かれる場面で根拠を確認する練習をすると伸びます。':score>=50?'基本知識はあります。個人情報、著作権、AIの誤情報などを具体的な場面で復習しましょう。':'まずは安全な使い方の基礎を確認しましょう。急いで共有せず、先生や関係者に確認する習慣が大切です。'; const next=isPassing(score)?'<h3>レベル2に向けた心構え</h3><p>次のレベルでは、知識を覚えるだけでなく、条件が変わった時に何を確認すべきかを考える力が重要です。AIの回答やネット情報を使う前に、根拠・同意・個人情報・公平性を一呼吸おいて確認しましょう。</p>':''; return `<div class="advice"><h3>総合評価</h3><p>${summary}</p><h3>良かった点</h3><p>${fieldLabel(best)}の判断が比較的安定しています。この調子で、理由を説明できるようにしていきましょう。</p><h3>今後伸ばしたい点</h3><p>${fieldLabel(weak)}を重点的に復習しましょう。${fieldAdvice(weak)}</p><h3>弱点克服法</h3><ul><li>間違えた問題は、正しい選択肢だけでなく「なぜ他の選択肢が弱いのか」を読み直しましょう。</li><li>学校生活・授業・校務の場面に置き換えて、誰に確認するべきかを考えましょう。</li><li>AIやインターネットの情報は、出典・日付・個人情報・著作権を確認してから使いましょう。</li></ul>${next}</div>`; }
function render(){ const stats=87+(passed?1:0); const app=document.getElementById('app')!; app.innerHTML=`<header class="hero"><p>WASEGAKU</p><h1>ICT・AI SKILL QUEST</h1><strong>― 知識だけでは攻略できない。判断力で挑め。―</strong><div class="toolbar"><button id="theme">現在: ${theme==='light'?'ライト':'ダーク'}</button><button id="sound">サウンド${sound?'ON':'OFF'}</button><button id="motion">動きを減らす${reduced?'ON':'OFF'}</button><a class="button" target="_blank" href="${location.href}">別タブでアプリを開く</a></div></header>${window.self!==window.top?'<p class="notice">Google Sites埋め込み表示です。ログインできない場合は別タブで開いてください。</p>':''}<div id="view"></div>`; document.getElementById('theme')!.onclick=()=>{theme=saveTheme(theme==='light'?'dark':'light');render()}; document.getElementById('sound')!.onclick=()=>{sound=saveSound(!sound); if(sound) void beep(8); render()}; document.getElementById('motion')!.onclick=()=>{reduced=!reduced;render()}; const root=document.getElementById('view')!;
 if(view==='home') root.innerHTML=`<section><h2>ダッシュボード</h2><p>${h(user.name)}（${user.school}・${user.role}） 残り挑戦回数: ${remainingAttempts(1)}回 / 今日: ${tokyoDateKey(new Date())}</p><div class="meter"><b>学園全体でレベル1合格者100人を目指そう！</b><progress value="${stats}" max="100"></progress><span>${stats}/100人 達成率${stats}% あと${Math.max(0,100-stats)}人</span></div><div class="levels">${levels.map(l=>`<article class="card"><h3>${l.title} ${l.status==='preparing'?'🔒':''}</h3><p>${l.difficulty}</p><p>${l.level===1?(passed?'✅ 合格済み':'▶ 現在挑戦可能'):'準備中'}</p><p>${l.level===1?stats:0}人合格</p>${l.level===1&&!passed?'<button id="start">挑戦開始</button>':''}</article>`).join('')}</div><button id="admin">管理者画面（権限はサーバー側で判定）</button></section>`;
 if(view==='quest') root.innerHTML=`<section><h2>レベル1クエスト</h2><p role="timer">制限時間 15:00（本番はサーバー開始時刻基準）</p>${clientQuestions.map((q,i)=>`<article class="question"><h3>問${i+1}: ${h(q.prompt)}</h3>${q.choices.map(c=>`<button data-q="${q.id}" data-c="${c.id}" ${answers[q.id]!==undefined?'disabled':''}>${h(c.text)}</button>`).join('')}${answers[q.id]!==undefined?`<p class="feedback">獲得点 ${answers[q.id]}点。${questions.find(x=>x.id===q.id)!.explanation}</p>`:''}</article>`).join('')}<button id="finish">終了して結果を見る</button></section>`;
 if(view==='result') root.innerHTML=`<section class="${passed&&!reduced?'celebrate':''}"><h2>${passed?'🎉 合格 LEVEL 1 CLEAR！ ICT・AIルーキー認定':'結果'}</h2><p>総合得点: ${total()}点</p><p>出題構成: ${fieldSummary()}</p>${resultAdvice()}${passed?`<p>修了証番号: ${cert}</p><button id="pdf">修了証を印刷表示</button>`:''}<button id="home">トップへ</button></section>`;
 if(view==='admin') root.innerHTML=`<section><h2>管理者画面</h2><p>管理者権限、問題、合格、修了証、集計はFirebaseでサーバー側検証します。</p><pre>${h(JSON.stringify({allowedDomain:isAllowedWorkspaceEmail(user.email), normalizedName:normalizeUsername(user.name), questions:questions.length, fields:fieldCounts(questions)},null,2))}</pre><button id="home">戻る</button></section>`;
 document.getElementById('start')?.addEventListener('click',()=>{view='quest';render()}); document.getElementById('admin')?.addEventListener('click',()=>{view='admin';render()}); document.getElementById('home')?.addEventListener('click',()=>{view='home';render()}); document.getElementById('finish')?.addEventListener('click',()=>{passed=isPassing(total()); if(passed){cert=nextCertificateNumber(1,2026,'A',1); void beep(10)} view='result';render()}); document.getElementById('pdf')?.addEventListener('click',()=>{const w=open('','_blank'); w?.document.write(`<h1>ICT・AI SKILL QUEST 修了証</h1><p>${h(user.name)} ${maskEmail(user.email)}</p><p>${cert}</p><p>検証URL: ${location.href}#verify/${cert}</p>`); w?.print()}); root.querySelectorAll<HTMLButtonElement>('[data-q]').forEach(b=>b.onclick=()=>{const q=questions.find(x=>x.id===b.dataset.q)!; const c=q.choices.find((x)=>x.id===b.dataset.c)!; if(answers[q.id]===undefined){answers[q.id]=c.score; void beep(c.score); render();}})
}
render();
